version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      VET_REDIS_URL: redis://redis:6379/0
      STREAM_REDIS_HOST: redis
      STREAM_REDIS_PORT: "6379"
      STREAM_REDIS_SSL: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service_account.json
    volumes:
      - ./service_account.json:/secrets/service_account.json:ro
    depends_on:
      - redis
    ports:
      - "8000:8080"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      STREAM_REDIS_HOST: redis
      STREAM_REDIS_PORT: "6379"
      STREAM_REDIS_SSL: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service_account.json
    volumes:
      - ./service_account.json:/secrets/service_account.json:ro
    depends_on:
      - redis
    ports:
      - "8081:8080"   # health endpoint
    restart: unless-stopped

  # NEW: Vet workflow worker (TaskIQ)
  vet_worker:
    build:
      context: .
      dockerfile: apps/vet_worker/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      VET_REDIS_URL: redis://redis:6379/0
      VET_STREAM: taskiq:vet
      STREAM_REDIS_HOST: redis
      STREAM_REDIS_PORT: "6379"
      STREAM_REDIS_SSL: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service_account.json
    volumes:
      - ./service_account.json:/secrets/service_account.json:ro
    depends_on:
      - redis
    ports:
      - "8082:8080"   # health endpoint
    restart: unless-stopped

  # NEW: Vet-chat worker (TaskIQ + OpenAI Responses)
  vet_chat_worker:
    build:
      context: .
      dockerfile: apps/vet_chat_worker/Dockerfile
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0                # TaskIQ broker URL
      STREAM_REDIS_HOST: redis                       # for streaming deltas to relay
      STREAM_REDIS_PORT: "6379"
      STREAM_REDIS_SSL: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service_account.json
      # Optional GPT-5 settings (or put them in .env)
      # VET_CHAT_MODEL: gpt-5
      # VET_CHAT_INSTRUCTIONS: "You are a helpful veterinary assistant."
      # VET_CHAT_VERBOSITY: medium
      # VET_CHAT_REASONING_EFFORT: low
      # VET_CHAT_MAX_OUTPUT_TOKENS: "800"
      # OPENAI_BASE_URL: "https://api.openai.com/v1"  # only if using a proxy/gateway
    volumes:
      - ./service_account.json:/secrets/service_account.json:ro
    depends_on:
      - redis
    ports:
      - "8083:8080"   # health endpoint
    restart: unless-stopped

  relay:
    build:
      context: .
      dockerfile: apps/relay/Dockerfile
    env_file: .env
    environment:
      STREAM_REDIS_HOST: redis
      STREAM_REDIS_PORT: "6379"
      STREAM_REDIS_SSL: "false"
    depends_on:
      - redis
    ports:
      - "8001:8080"
    restart: unless-stopped

volumes:
  redis-data:
